language: c
cache: apt
sudo: true

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libjack-dev libasound2-dev; fi

compiler:
    - gcc
   #- g++
    - clang

script: 
    - ./configure
    - cd build && make
